language: go
go:
- 1.13.3
env:
  global:
  - GO111MODULE=on
  - PATH=$PATH:/usr/local/kubebuilder/bin
services:
- docker
jobs:
  include:
  - stage: build
    script: make build-ci
  - stage: push
    script: make push-ci
stages:
- build
- name: push
  if: branch = master
