language: go
go:
  - 1.13.3

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - env GO111MODULE=on make docker-build
  - make docker-push
